# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Acme\StoreBundle\Document\User: bcrypt


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            entity: {class: Acme\StoreBundle\Document\User, property: login}

        in_memory:
            memory:
                users:
                    admin:
                        password: rabbit
                        roles: "ROLE_ADMIN"

    firewalls:
            main:
                anonymous: ~
                form_login:
                    login_path: login
                    check_path: login_check
                logout:
                    path: /logout
                    target: /