<?php

namespace Acme\StoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends DocumentRepository
{
	public function findAll() {
		return $this
            ->createQueryBuilder()
			->sort("name", "ASC")
			->getQuery()
			->execute();	
	}

	public function findSortedByDate() {
        return $this
            ->createQueryBuilder()
            ->sort("date", "DESC")
            ->getQuery()
            ->execute();
    }

    public function getByCategory($category) {
        return $this
            ->createQueryBuilder()
            ->field('category')->equals($category)
            ->getQuery()
            ->execute();
    }

    public function getByEntry($namePart) {
	    $func = "function() { return (/" . $namePart. "/).test(this.name)}";
	    return $this
            ->createQueryBuilder()
            ->where($func)
            ->getQuery()
            ->execute();
    }

    public function findById($id) {
	    return iterator_to_array($this
            ->createQueryBuilder()
            ->field("_id")
            ->equals($id)
            ->getQuery()
            ->execute());
    }


}
